"""Add output_format to files

Revision ID: 9b9abb09220a
Revises: 5c80bc23950b
Create Date: 2025-05-22 22:04:29.968451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9abb09220a'
down_revision: Union[str, None] = '5c80bc23950b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('output_format', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'output_format')
    # ### end Alembic commands ###
